[env:m5stickc-plus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
board_build.f_cpu = 160000000L
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5Unified
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
